"""
alerts/email_alert.py
----------------------
HTML email summary for the SEPA daily screening pipeline.

Uses only Python standard-library modules (``smtplib`` + ``email.mime``).
No third-party SMTP libraries are required.

Config keys (under ``config["alerts"]["email"]``):
    enabled      — bool, default False
    smtp_host    — SMTP server hostname
    smtp_port    — SMTP server port (default 587)
    smtp_user    — Login username / sender address
    smtp_pass    — Login password (loaded upstream from env)
    recipients   — list[str] of recipient addresses

Credentials may also be provided as environment variables
``SMTP_USER`` and ``SMTP_PASS`` (loaded upstream; read from config here).
"""

from __future__ import annotations

import os
import smtplib
from datetime import date
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from rules.scorer import SEPAResult
from utils.logger import get_logger

log = get_logger(__name__)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _top5_table_html(results: list[SEPAResult]) -> str:
    """Return an HTML <table> of the top-5 candidates by score."""
    top5 = sorted(results, key=lambda r: r.score, reverse=True)[:5]
    rows_html = ""
    for r in top5:
        entry = f"₹{r.entry_price:,.0f}" if r.entry_price else "—"
        stop = f"₹{r.stop_loss:,.0f}" if r.stop_loss else "—"
        risk = f"{r.risk_pct:.1f}%" if r.risk_pct else "—"
        breakout = "✅" if r.breakout_triggered else "—"
        rows_html += (
            f"<tr>"
            f"<td><b>{r.symbol}</b></td>"
            f"<td>{r.setup_quality}</td>"
            f"<td>{r.score}</td>"
            f"<td>{r.rs_rating}</td>"
            f"<td>{entry}</td>"
            f"<td>{stop}</td>"
            f"<td>{risk}</td>"
            f"<td>{breakout}</td>"
            f"</tr>\n"
        )
    return (
        "<table border='1' cellpadding='4' cellspacing='0' style='border-collapse:collapse;font-family:monospace'>"
        "<tr style='background:#2c3e50;color:white'>"
        "<th>Symbol</th><th>Grade</th><th>Score</th><th>RS</th>"
        "<th>Entry</th><th>Stop</th><th>Risk</th><th>Breakout</th>"
        "</tr>\n"
        + rows_html
        + "</table>"
    )


def _build_html_body(results: list[SEPAResult], run_date: date) -> str:
    """Build the full HTML email body."""
    a_plus = [r for r in results if r.setup_quality == "A+"]
    a_grade = [r for r in results if r.setup_quality == "A"]
    b_grade = [r for r in results if r.setup_quality == "B"]
    table = _top5_table_html(results) if results else "<p>No qualifying setups today.</p>"
    return f"""<!DOCTYPE html>
<html><body style="font-family:Arial,sans-serif;max-width:800px;margin:auto">
<h2 style="color:#2c3e50">SEPA Watchlist — {run_date}</h2>
<p>
  <b>A+:</b> {len(a_plus)} &nbsp;|&nbsp;
  <b>A:</b> {len(a_grade)} &nbsp;|&nbsp;
  <b>B:</b> {len(b_grade)} &nbsp;|&nbsp;
  <b>Total screened:</b> {len(results)}
</p>
<h3>Top Candidates</h3>
{table}
<p style="color:#7f8c8d;font-size:12px">
  Generated by SEPA AI Screener · Full report attached.
</p>
</body></html>"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def send_daily_summary(
    results: list[SEPAResult],
    html_report_path: str,
    config: dict,
    run_date: date,
) -> bool:
    """Send an HTML email summary with the watchlist report attached.

    Returns ``True`` if the email was sent successfully, ``False`` if skipped
    (disabled, missing credentials) or if SMTP raised an error.
    """
    email_cfg = config.get("alerts", {}).get("email", {})
    if not email_cfg.get("enabled", False):
        log.info("Email alerts disabled in config — skipping")
        return False

    smtp_host: str = str(email_cfg.get("smtp_host", ""))
    smtp_port: int = int(email_cfg.get("smtp_port", 587))
    smtp_user: str = str(email_cfg.get("smtp_user") or os.environ.get("SMTP_USER", ""))
    smtp_pass: str = str(email_cfg.get("smtp_pass") or os.environ.get("SMTP_PASS", ""))
    recipients: list[str] = list(email_cfg.get("recipients", []))

    if not smtp_host or not smtp_user or not smtp_pass or not recipients:
        log.warning("Email alert skipped: incomplete SMTP credentials or no recipients")
        return False

    a_plus_count = sum(1 for r in results if r.setup_quality == "A+")
    a_count = sum(1 for r in results if r.setup_quality == "A")

    subject = (
        f"SEPA Watchlist — {run_date} — "
        f"{a_plus_count} A+ | {a_count} A setups"
    )
    html_body = _build_html_body(results, run_date)

    # ── Assemble MIME message ────────────────────────────────────────────────
    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = ", ".join(recipients)

    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # ── Attach HTML report if it exists ─────────────────────────────────────
    report_path = Path(html_report_path)
    if report_path.exists():
        with report_path.open("rb") as fh:
            attachment = MIMEApplication(fh.read(), _subtype="html")
            attachment.add_header(
                "Content-Disposition",
                "attachment",
                filename=f"watchlist_{run_date}.html",
            )
            msg.attach(attachment)
    else:
        log.warning("Email: HTML report not found at %s — attaching skipped", report_path)

    # ── Send via SMTP ────────────────────────────────────────────────────────
    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.login(smtp_user, smtp_pass)
            smtp.sendmail(smtp_user, recipients, msg.as_string())
        log.info("Email sent to %s (subject: %s)", recipients, subject)
        return True
    except smtplib.SMTPException as exc:
        log.error("SMTP error sending daily summary: %s", exc)
        return False
    except OSError as exc:
        log.error("Network error sending daily summary: %s", exc)
        return False
