"""
tests/integration/test_feature_pipeline_e2e.py
-----------------------------------------------
End-to-end integration test for the full feature computation pipeline.

Uses the deterministic synthetic fixture files generated by:
    python scripts/create_test_fixtures.py

Tests cover:
    1. bootstrap() produces a feature file with ALL expected columns
    2. rs_raw column is present but NaN after bootstrap (filled later by RS pass)
    3. update() appends exactly 1 new row to an already-bootstrapped feature file
    4. needs_bootstrap() returns False after a successful bootstrap
    5. needs_bootstrap() returns True for a symbol that has never been bootstrapped

Performance requirement
-----------------------
Bootstrap of a 300-row symbol must complete in < 2 seconds on any machine.
"""

from __future__ import annotations

import shutil
import time
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from features.feature_store import bootstrap, needs_bootstrap, update
from storage.parquet_store import read_parquet, write_parquet

# ---------------------------------------------------------------------------
# Constants — expected feature columns after bootstrap
# ---------------------------------------------------------------------------

EXPECTED_COLUMNS: list[str] = [
    # moving_averages
    "sma_10", "sma_21", "sma_50", "sma_150", "sma_200",
    "ema_21", "ma_slope_50", "ma_slope_200",
    # atr
    "atr_14", "atr_pct",
    # volume
    "vol_50d_avg", "vol_ratio", "up_vol_days", "down_vol_days", "acc_dist_score",
    # pivot
    "pivot_high", "pivot_low", "pivot_high_idx", "pivot_low_idx",
    # vcp
    "vcp_contraction_count", "vcp_max_depth_pct", "vcp_final_depth_pct",
    "vcp_vol_ratio", "vcp_base_length_weeks", "vcp_base_low",
    "vcp_valid", "vcp_tightness_score",
    # relative strength — present but NaN (filled by the cross-symbol RS pass)
    "rs_raw",
]

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures"
_MOCKUP_FIXTURE = FIXTURE_DIR / "sample_ohlcv_MOCKUP.parquet"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_config(tmp_path: Path) -> dict:
    """Minimal config dict pointing data directories at *tmp_path*."""
    return {
        "data": {
            "processed_dir": str(tmp_path / "processed"),
            "features_dir":  str(tmp_path / "features"),
        },
        "stage": {
            "ma200_slope_lookback": 20,
            "ma50_slope_lookback": 10,
        },
        "atr":    {"period": 14},
        "volume": {"avg_period": 50, "lookback_days": 20},
        "vcp": {
            "detector": "rule_based",
            "pivot_sensitivity": 5,
            "min_contractions": 2,
            "max_contractions": 5,
            "require_declining_depth": True,
            "require_vol_contraction": True,
            "min_weeks": 3,
            "max_weeks": 52,
            "tightness_pct": 10.0,
            "max_depth_pct": 50.0,
        },
        "rs": {"period": 63},
    }


def _install_fixture(config: dict, symbol: str, fixture_path: Path) -> None:
    """Copy *fixture_path* into the processed dir under *symbol*.parquet."""
    proc_dir = Path(config["data"]["processed_dir"])
    proc_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy(fixture_path, proc_dir / f"{symbol}.parquet")


def _features_path(config: dict, symbol: str) -> Path:
    return Path(config["data"]["features_dir"]) / f"{symbol}.parquet"


def _extend_processed(config: dict, symbol: str) -> date:
    """Append one new business-day row to the processed Parquet file.

    Returns the new row's date so the caller can pass it to update().
    """
    proc_path = Path(config["data"]["processed_dir"]) / f"{symbol}.parquet"
    df = read_parquet(proc_path)
    last_ts = df.index[-1]
    new_ts  = last_ts + pd.offsets.BDay(1)

    rng = np.random.default_rng(999)
    prev_close = float(df["close"].iloc[-1])
    new_close  = prev_close + float(rng.normal(0.5, 0.5))
    new_close  = max(new_close, 1.0)
    new_row = pd.DataFrame(
        {
            "open":   [new_close + float(rng.uniform(-0.3, 0.3))],
            "high":   [new_close + float(rng.uniform(0.5, 1.5))],
            "low":    [new_close - float(rng.uniform(0.5, 1.5))],
            "close":  [new_close],
            "volume": [float(rng.integers(500_000, 5_000_000))],
        },
        index=pd.DatetimeIndex([new_ts]),
    )
    # Clamp to valid OHLCV
    new_row["low"]  = np.maximum(new_row["low"],  1.0)
    new_row["high"] = np.maximum(new_row["high"], new_row["close"])
    new_row["low"]  = np.minimum(new_row["low"],  new_row["close"])

    extended = pd.concat([df, new_row])
    write_parquet(proc_path, extended)
    return pd.Timestamp(new_ts).date()



# ---------------------------------------------------------------------------
# Guard: skip the whole module if fixture files are missing
# ---------------------------------------------------------------------------

def pytest_configure(config):  # noqa: ARG001
    pass  # nothing needed here; pytestmark handles it per-test


# ---------------------------------------------------------------------------
# E2E Test Class
# ---------------------------------------------------------------------------

@pytest.mark.slow
class TestFeaturePipelineE2E:
    """End-to-end integration tests for the feature computation pipeline.

    All tests in this class use the MOCKUP fixture (300 rows, Stage 2 uptrend).
    Each test runs in an isolated tmp_path directory — no shared state.
    """

    # ------------------------------------------------------------------
    # Test 1 + 2 + 4: bootstrap() produces correct output
    # ------------------------------------------------------------------

    def test_bootstrap_creates_feature_file_with_expected_columns(
        self, tmp_path: Path
    ) -> None:
        """Bootstrap 300-row MOCKUP symbol must complete in < 2 seconds.

        Checks:
        * Feature file is created.
        * It has exactly 300 rows (one per input row).
        * All EXPECTED_COLUMNS are present.
        * rs_raw column is present AND every value is NaN (not yet filled).
        """
        if not _MOCKUP_FIXTURE.exists():
            pytest.skip("Fixture file missing — run scripts/create_test_fixtures.py first")

        config = _make_config(tmp_path)
        _install_fixture(config, "MOCKUP", _MOCKUP_FIXTURE)

        # Bootstrap 300-row symbol must complete in < 2 seconds on any machine.
        t0 = time.perf_counter()
        bootstrap("MOCKUP", config)
        elapsed = time.perf_counter() - t0

        assert elapsed < 2.0, (
            f"bootstrap() took {elapsed:.3f}s — must be < 2.0s for a 300-row symbol"
        )

        fp = _features_path(config, "MOCKUP")
        assert fp.exists(), "Feature Parquet file was not created by bootstrap()"

        df = read_parquet(fp)
        assert len(df) == 300, f"Expected 300 rows, got {len(df)}"

        missing = [c for c in EXPECTED_COLUMNS if c not in df.columns]
        assert not missing, f"Missing columns after bootstrap: {missing}"

        # rs_raw must be present but NaN everywhere
        assert "rs_raw" in df.columns, "rs_raw column is absent from feature file"
        assert df["rs_raw"].isna().all(), (
            "rs_raw should be all-NaN after bootstrap (filled by RS pass later); "
            f"found {df['rs_raw'].notna().sum()} non-NaN values"
        )

    # ------------------------------------------------------------------
    # Test 3: update() appends 1 new row
    # ------------------------------------------------------------------

    def test_update_appends_one_new_row(self, tmp_path: Path) -> None:
        """update() must append exactly 1 row to the already-bootstrapped file."""
        if not _MOCKUP_FIXTURE.exists():
            pytest.skip("Fixture file missing — run scripts/create_test_fixtures.py first")

        config = _make_config(tmp_path)
        _install_fixture(config, "MOCKUP", _MOCKUP_FIXTURE)
        bootstrap("MOCKUP", config)

        n_before = len(read_parquet(_features_path(config, "MOCKUP")))

        new_date = _extend_processed(config, "MOCKUP")
        update("MOCKUP", new_date, config)

        df_after = read_parquet(_features_path(config, "MOCKUP"))
        assert len(df_after) == n_before + 1, (
            f"Expected {n_before + 1} rows after update(), got {len(df_after)}"
        )

    # ------------------------------------------------------------------
    # Test 4: needs_bootstrap() returns False after bootstrap
    # ------------------------------------------------------------------

    def test_needs_bootstrap_false_after_bootstrap(self, tmp_path: Path) -> None:
        """needs_bootstrap() must return False once bootstrap() has run."""
        if not _MOCKUP_FIXTURE.exists():
            pytest.skip("Fixture file missing — run scripts/create_test_fixtures.py first")

        config = _make_config(tmp_path)
        _install_fixture(config, "MOCKUP", _MOCKUP_FIXTURE)

        assert needs_bootstrap("MOCKUP", config) is True, (
            "Precondition: needs_bootstrap should be True before bootstrap"
        )
        bootstrap("MOCKUP", config)
        assert needs_bootstrap("MOCKUP", config) is False, (
            "needs_bootstrap should be False after a successful bootstrap"
        )

    # ------------------------------------------------------------------
    # Test 5: needs_bootstrap() returns True for unknown symbol
    # ------------------------------------------------------------------

    def test_needs_bootstrap_true_for_nonexistent_symbol(
        self, tmp_path: Path
    ) -> None:
        """needs_bootstrap() must return True when the feature file does not exist."""
        config = _make_config(tmp_path)
        assert needs_bootstrap("NONEXISTENT", config) is True, (
            "needs_bootstrap must be True for a symbol with no feature file"
        )
